### ISSUE TITLE
[RJ] : [Update] : [Map] - New Terrian Suggestions

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#106]
**Describe the update**
We were thinking of changing the way the terrian / map setup! We would love to get some feedback and suggestions.
* * *

**References for update**
Please post below any suggestions / concepts that you might want to add into the game!

* * *

**Security risk**
Are there any major security risks?! 
None but there might be performance risks if we load too many maps later down the line.

* * *

**Comment by zanerage** [comment]
here are some of my suggestions:
• https://assetstore.unity.com/packages/3d/environments/landscapes/terrain-sample-asset-pack-145808
• https://assetstore.unity.com/packages/tools/terrain/terrain-creator-low-poly-146834
• https://assetstore.unity.com/packages/3d/environments/landscapes/lunar-landscape-3d-132614
• https://assetstore.unity.com/packages/3d/environments/landscapes/winter-zone-mini-107583
• https://assetstore.unity.com/packages/3d/environments/landscapes/mars-landscape-3d-175814
• https://assetstore.unity.com/packages/3d/environments/sci-fi/martian-surface-rocky-area-186736

**Comment by h0lybyte** [comment]
Since we are limited to WebGL, we might stick with a generic void / space background because of performance issues. We can come back to more abstract terrains when we are building for PC/Console.

**Comment by h0lybyte** [comment]
- https://assetstore.unity.com/packages/3d/environments/sci-fi/sci-fi-styled-modular-pack-82913
- https://assetstore.unity.com/packages/3d/environments/sci-fi/modular-sci-fi-corridor-142811

Going to add those two right now.

**Comment by h0lybyte** [comment]
We have a new Terrain issue that we can reference, thus closing this out.
