### ISSUE TITLE
[RJ] : [Update] : Crate Model

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#108]
**Describe the Update/Upgrade/Issue**
Incase we need a crate model , I found one that is URP ready.

* * *

**References for Update**
Unity Asset Store Model : https://assetstore.unity.com/packages/3d/props/sci-fi-crate-low-poly-free-urp-173856

* * *

**Security/Performance Risk**
Are there any major security risks?!
There should not be.
* * *

**Comment by zanerage** [comment]
We should get this for the LOOT crate, the player opens and we add more items to the pool table with this.

**Comment by h0lybyte** [comment]
Okay the crate was rendered and it looks like it works fine.
