### ISSUE TITLE
Traefik Plugins

### ISSUE THREAD

**Issue by ygtripps** [KBVE/kbve.com#11]
Plugin wise from what I've found:
[Fail2ban](https://plugins.traefik.io/plugins/628c9ebcffc0cd18356a979f/fail2-ban)
[Log4J](https://plugins.traefik.io/plugins/628c9ec2ffc0cd18356a97a2/log4-shell)
[RealIP](https://plugins.traefik.io/plugins/628c9f01108ecc83915d776c/traefik-real-ip)

**Comment by h0lybyte** [comment]
Going upon these plugins, I found a decent gist that breaks down their "complete" solution.

https://gist.github.com/saniaky/dc75cbf64922e418400b0f54ed5b2c3a. 

We could definitely add some of this to our eco-system.

**Comment by h0lybyte** [comment]
This has been pending.

- Fail2Ban with Cloudlfare integration and a couple active repos. 
- Across the block ban for almost every country besides USA/CA. [Still in progress]
- We will skip the log4j, as Snyk and several other services can handle that
- RealIP , well everything is under CloudFlare , so we can easily pass through the RealIP from them, while it goes through all our reverse proxies.
