### ISSUE TITLE
[RJ] : [Update] : Weapons URP

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#110]
**Describe the Update/Upgrade/Issue**
A couple weapons for URP-ready that we could add.

I will update the list based upon what I find. Furthermore, I will migrate these to the unity notes, for future reference. 

* * *

**References for Update**
Include any links / data for the update that must be done.

[1] Laser Rifle 3D - https://www.turbosquid.com/3d-models/cartoony-laser-rifle-3d-model-1979586
[2] DMR - https://www.turbosquid.com/3d-models/3d-scifi-dmr-model-1983451
* * *

**Security/Performance Risk**
Are there any major security risks?!
No major performance issues yet, but too many models might make the game too heavy. We should stick to around 3-5 and then rotate out the type of animation / ammo that they have.

* * *

**Comment by zanerage** [comment]
56.000 Triangle but yeah I mean it is URP. But we can try them and see how WEBGL handles it.  Both guns look good for sure. It would be excellent addition to the game,

**Comment by h0lybyte** [comment]
We will close this out as well, as the issue for weapons has been resolved a while back.
