### ISSUE TITLE
[Update] : [Lottie] : Interactivity

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#114]
**Describe the update**

Adding interactive animations to `lottie` elements via React states.
- I started the core component located at `Element\Lottie\Interactive` but I am going to delay working on it, as there are some more pressing issues to address. 

- I am keeping this here as a note / reference, for when I go back to look at it.

* * *

**Comment by RangerDevv** [comment]
May I know what you mean my interactivity @h0lybyte ?
