### ISSUE TITLE
[RJ] : [Bug] : Memory Leak on Login Screen

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#119]
**Describe the Update/Upgrade/Issue**
When I am running the LoginMenu, I sometimes encounter this error within the logs
`A Native Collection has not been disposed, resulting in a memory leak. Enable Full StackTraces to get more details.`

I am currently looking into why this comes up.
* * *

**References for Update**
Nothing yet, but I will add this into the `Notes` for `Unity`
* * *

**Security/Performance Risk**
Memory leaks are a meme and a nightmare xD

* * *

**Comment by h0lybyte** [comment]
Okay unity would be trolling.

Reference -> https://gamedev.stackexchange.com/questions/186134/a-native-collection-has-not-been-disposed-resulting-in-a-memory-leak-enable-fu

Unity 2020+, in it's infinite wisdom, [removed the ability](https://forum.unity.com/threads/visibility-changes-for-preview-packages-in-2020-1.910880/) for you to easily find the cause for this message. They provided a workaround, but as you will see following these steps, it is extremely hacky:

Go Window -> Package Manager
Click the + icon at the topleft, select add package from git URL
Enter com.unity.jobs (It's not a git URL, but that's what Unity [wants](https://forum.unity.com/threads/visibility-changes-for-preview-packages-in-2020-1.910880/#post-6026342) you to do)
You now have the Jobs tab at the top of your Editor.

Go Jobs -> Leak Detection -> Full Stack Traces (Expensive)
Close and open the editor again, then rerun the game

**Comment by zanerage** [comment]
Does it show where memory leaks? yes, you can enable full stack traces in unity. Let me know if you get an update on this

**Comment by h0lybyte** [comment]
Yeah it was resolved, it is the way I was handling the coroutines ~
