### ISSUE TITLE
[RJ] : [Update] : Stylized Robots Humanoid Rig

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#133]
**Describe the Update/Upgrade/Issue**

Model Request: https://assetstore.unity.com/packages/3d/characters/robots/stylized-robots-humanoid-rig-155490

My concern might be in the animations? We might have to customize it a bit more, I suppose.

* * *

**References for Update**
[Asset Store](https://assetstore.unity.com/packages/3d/characters/robots/stylized-robots-humanoid-rig-155490)

* * *

**Security/Performance Risk**
Are there any major security risks?!
No major performance risk, as we are shifting the build to Desktop, rather than mobile / webGL.

* * *

**Comment by zanerage** [comment]
Animations are free on mixamo.com you can take a look. And then we put them inside Emerald ai and you got your working enemies.

**Comment by h0lybyte** [comment]
Okay we can close this out as an issue for now. 

I saw some of the models that you suggested, we can use those within our first planet.
