### ISSUE TITLE
[RJ] : [Update] : Robot Elliot

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#134]
**Describe the Update/Upgrade/Issue**

We could have the robot be a campanion to the player? Like it follows them around and maybe helps with the missions. The factor of animation would be within question.

* * *

**References for Update**
Asset [Store](https://assetstore.unity.com/packages/3d/characters/robots/robot-elliot-112654)
* * *

**Security/Performance Risk**
Are there any major security risks?! No.

* * *

**Comment by zanerage** [comment]
We can solve animation with emerald AI.  I already own it so you don't need to buy it.
We can use it for companionship also so it can fight by your side.
Also, we can put his power-ups inside the player talent tree.

**Comment by h0lybyte** [comment]
Okay we can close this out and come back to it when it becomes a major issue.
