### ISSUE TITLE
[RJ] : [Update] : Terrian Packs

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#135]
**Describe the Update/Upgrade/Issue**
Okay I will put all the terrian packs , for now, into this one issue and we can see which ones we want to add.

* * *

**References for Update**
[1] [Alien Terrian Pack](https://assetstore.unity.com/packages/3d/environments/landscapes/alien-terrain-pack-38488)
[2] [SciFi Platform City](https://assetstore.unity.com/packages/3d/environments/sci-fi/scifi-platform-city-111073)
[3] [SciFi Facility](https://assetstore.unity.com/packages/3d/environments/sci-fi/sci-fi-facility-116916)
[4] [SciFi Slums](https://assetstore.unity.com/packages/3d/environments/urban/newgen-sci-fi-slums-211172)

* * *

**Security/Performance Risk**
Are there any major security risks?!
We just have to be careful not to go too crazy lmfao.

* * *

**Comment by zanerage** [comment]
I think number [1] for outside of the city environment and [4] sci-fi slums are good to have city inside the map. 
As we are moving now to the open world we could use this as a big map.
The story Would be like this: You start outside in the wild and you fight your way to the town where you face final enemies and the boss for a final fight to save humanity from tyranny who is led by an evil guy(android).
Player get stronger by finding upgrades and looting towards the town and preparing for a big fight.

**Comment by h0lybyte** [comment]
Player starts off in their base aka lobby and then the first mission aka  [mission 0 would be the tutorial] where they are doing what you are suggesting?

**Comment by h0lybyte** [comment]
Okay going to add the terrain packs next.

**Comment by h0lybyte** [comment]
We will close this issue for now, as we have one terrian pack ready and do not need the others for now.

We will create a new issue once we are ready to add another terrian pack.

Fyi , the current pack is for the alien planet.
