### ISSUE TITLE
[RJ] : [Update] : Inventory Idea for the Game

### ISSUE THREAD

**Issue by zanerage** [KBVE/kbve.com#136]
**Describe the Update/Upgrade/Issue**
Using Inventory System for RogueJester
This one could give us all we need

* * *

**References for Update**
[1] https://assetstore.unity.com/packages/tools/game-toolkits/ultimate-inventory-system-166053#description

* * *

**Security/Performance Risk**
No risk we gain on time for not making it from scratch.

* * *

**Comment by h0lybyte** [comment]
https://github.com/devdogio/Inventory-Pro

It's open source and has a ton of implementations.

**Comment by h0lybyte** [comment]
Ah yeah this Inventory-Pro is very old whereas the other one is up to date. 

I think we should go with the Ultimate Inventory System

**Comment by zanerage** [comment]
Issues with Inventory
![image](https://user-images.githubusercontent.com/20169150/203816584-c7db74ac-3000-4523-8f7e-7f125237ac58.png)
Also 505 errors on uploading the folder
![image](https://user-images.githubusercontent.com/20169150/203816698-2eef3202-dd7b-48c1-a356-c5d3af9a9794.png)
It uses an old version of unity 2018. At that time TMPro also wasn't supported.
It is supported since 2019.4
It is using the old unity UI system also which is not supported by our versions.
And other issues that come with that version. The list will be long...

**Comment by h0lybyte** [comment]
Okay so I commited https://github.com/KBVE/roguejester/tree/beta-inventory

Take a look, there was some issues with the Input controller , so that might be of concern later down the line.

**Comment by h0lybyte** [comment]
It looks like inventory was added , at least for the basic beta.

Any inventory issue should be made now as its own specific issue.
