### ISSUE TITLE
[RJ] : [Update] : FPS Controller from Opsive Options

### ISSUE THREAD

**Issue by zanerage** [KBVE/kbve.com#138]
**Describe the Update/Upgrade/Issue**
We got opsive cheaper version to use the FPS controller. 
And the more expensive version with more details and functionality

* * *

**References for Update**
Version 1 [FPS Controller 65 $ (on discount)](https://assetstore.unity.com/packages/tools/game-toolkits/ufps-ultimate-fps-233711)
Version 2 [ULTIMATE FPS CONTROLLER 249$ ](https://assetstore.unity.com/packages/tools/game-toolkits/ultimate-character-controller-233710)

* * *

**Security/Performance Risk**
NO RISK ONLY GAINS!

* * *

**Comment by h0lybyte** [comment]
We will not being use FPS controller, so we can close this out and move forward with our hybrid controller.
