### ISSUE TITLE
[Update] : [discord.astro] : UI/UX additions

### ISSUE THREAD

**Issue by RangerDevv** [KBVE/kbve.com#167]
**Describe the update**
A clear and concise description of what the update will be. Keep it simple!

Add interactivity to discord.astro.

* * *

**References for update**
Include any links / data for the update that must be done.

No links or refs. 

* * *

**Comment by h0lybyte** [comment]
Any update on this end? @RangerDevv

**Comment by RangerDevv** [comment]
This has been closed. sorry I forgot lol.
