### ISSUE TITLE
Rpool-backup issue

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#21]
**Describe the bug**
We are having issues with storing backup data (for certain types) of VMs inside of rpool.

We can keep backups in the local storage, but we want to also have the rpool accept the file types.

* * *

**Comment by jzanecook** [comment]
Here is the documentation for Proxmox Storage: https://pve.proxmox.com/wiki/Storage

If we edit `/etc/pve/storage.cfg` and add "backup" to the `content` line under `dir: rpool-backup` and then restart we should be able to get it to be the right kinds.

This could also work to remove anything except ISO files from `dir: local`

**Comment by jzanecook** [comment]
```
[root@server ~]$ cat /etc/pve/storage.cfg 
zfspool: rpool-vmdata
        pool rpool/vmdata
        content images,rootdir
        mountpoint /rpool/vmdata
        sparse 1

dir: local
        path /var/lib/vz
        content rootdir,backup,images,iso,vztmpl
        prune-backups keep-all=1

dir: rpool-backup
        path /backup_rpool
        content backup,vztmp1
```

**Comment by h0lybyte** [comment]
We should run a test case of restoring the backups. 
I was able to add two different qEMUs into the backup pool. Now we have to test case the restoring aspect, just to make sure everything is `A-okay.`

**Comment by h0lybyte** [comment]
When I was working on #38 , I saw this in the logs

```
INFO: creating vzdump archive '/backup_rpool/dump/vzdump-qemu-100-2022_09_19-18_14_09.vma.zst'
INFO: skipping guest-agent 'fs-freeze', agent configured but not running?
INFO: started backup task 'd02509c2-7b6d-4ca6-8e78-064ac1eb05bd'
INFO: resuming VM again
```

`skipping guest-agent 'fs-freeze', agent configured but not running?`

**Comment by h0lybyte** [comment]
We were looking this issue the wrong way, we dont want to backup the whole VM. We actually want to only focus on backuping the specific `PersistentVolume`. Backuping up whole images of an ubuntu image that is running docker or k8s isnt worth the time, since they arnt important.  That is why VOID resolves this issue.
