### ISSUE TITLE
Concept: Updates to the install.sh for Discord

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#26]
**Core Concept/Theory**

We should look into having the install.sh script display the output AND log the information into a file.

* * *

**Comment by jzanecook** [comment]
- Send logs from outputs to both stdout as well as a script that will send it to the discord bot (potentially as well as a gist)
- OR send to strapi, more configuration in the future

**Comment by h0lybyte** [comment]
Initially we could have done this ->
- After Ansible runs, the output from the Ansible can be sent to the log pipe via websockets to Grafana -> Prometheus
- Repo Reference: https://github.com/golioth/grafana-websocket-plugin
