### ISSUE TITLE
Concept: Ship Through The Swarm

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#28]
**Core Concept/Theory**

We will be rebuilding the docker swarm with a custom ingress and a socket proxy. 

* * *

**Alternative Examples / sources/  Information**
Add any other context or examples of this concept here:
[1] https://www.rockyourcode.com/traefik-2-docker-swarm-setup-with-docker-socket-proxy-and-more/

* * *

We will also add any additional links here.

**Comment by h0lybyte** [comment]
From [Jacob_Griff ](https://www.reddit.com/r/docker/comments/xbtowp/loadbalancing_containers_between_multiple_remote/)

> You really have three levels of solutions.

> 1. Lightest: put portainer on one machine and add portainer agents to the other machines you want to control and balance containers yourself.

> 2. Use docker swarm and allow it to balance across the machines.

> 3. Use Kubernetes, whether a light version like k3s or microk8s or a full version like k8s.

> With each level you increase the software and learning overhead, but decrease your personal management overhead. I personally took the dive and use k3s to manager my machines.

So it seems that we will be moving to level 3.

**Comment by h0lybyte** [comment]
Possible issue that we might run into ->

[2] - https://hub.docker.com/r/containous/whoami
[3] - https://github.com/traefik/whoami

For the compose example for whoami. Will add more information on here later on.

**Comment by h0lybyte** [comment]
For Traefik VE Docker Compose , involving Secrets, within the Portainer environment.

Under the same space as environment, we should do

```
    secrets:
      - DOMAIN
      - EMAIL
      - TRAEFIK_ADMINS
      - WHITELIST_IP
      - USERNAME
 ```

At the end we will have the reference to the secrets. 

```
secrets:
  DOMAIN:
    external: true
  EMAIL:
    external: true
  TRAEFIK_ADMINS:
    external: true
  WHITELIST_IP:
    external: true
  USERNAME:
    external: true   
  ```

**Comment by h0lybyte** [comment]
```
    environment:
      # - Below will be the cloudflare information
      - CF_API_EMAIL=/run/secrets/CF_API_EMAIL
```
We did that as well ^

**Comment by jzanecook** [comment]
```
invalid interpolation format for services.deploy.labels.[]: "required variable DOMAIN is missing a value: Variable not set". You may need to escape any $ with another $.
```

**Comment by jzanecook** [comment]
https://stackoverflow.com/questions/48094850/docker-stack-setting-environment-variable-from-secrets

**Comment by h0lybyte** [comment]
Maybe this is what _FILE is? https://stackoverflow.com/questions/66177509/docker-swarm-use-secrets-for-enviroments-variable

**Comment by jzanecook** [comment]
services.deploy Additional property placement is not allowed

**Comment by jzanecook** [comment]
https://docs.docker.com/compose/compose-file/deploy/#placement

**Comment by jzanecook** [comment]
`services.volumes must be a mapping`

**Comment by h0lybyte** [comment]
> `services.deploy Additional property placement is not allowed`

It was because of an indent within the docker-compose; now looking into the mapping issue for the volumes.

**Comment by h0lybyte** [comment]
https://hub.docker.com/r/tecnativa/docker-socket-proxy
Not always needed
You will possibly need to grant access to some of these API sections, which are not so extremely critical but can expose some information that your service does not need.

`SWARM` ?

**Comment by h0lybyte** [comment]
https://stackoverflow.com/questions/67408934/portainer-docker-swarm-import-secrets-to-compose

**Comment by jzanecook** [comment]
https://docs.docker.com/compose/compose-file/#env_file

We can put all of the ENV variables into a config, specify the config in `configs`, and then specify the `env_file` to point to that config. **MAYBE**

**Comment by h0lybyte** [comment]
https://docs.portainer.io/user/docker/stacks/add
`Note: Using env_file to define a file does not work in Docker Swarm due to the lack of env_file support in docker stack deploy (used on Swarm environments to deploy your stack). On Docker Swarm, you will need to define each environment variable manually. `

Hmm

**Comment by jzanecook** [comment]
![Screenshot_20220912-142653_Chrome](https://user-images.githubusercontent.com/90814067/189739012-0a014bf1-33ab-4cf0-a3a1-0a097b358d29.png)

**Comment by h0lybyte** [comment]
`this is NOT the way`

**Comment by h0lybyte** [comment]
`time="2022-09-12T20:26:05Z" level=info msg="Starting provider *file.Provider {\"watch\":true,\"filename\":\"traefik_conf/dynamic_conf.toml\"}"
time="2022-09-12T20:26:05Z" level=error msg="Cannot start the provider *file.Provider: error reading configuration file: traefik_conf/dynamic_conf.toml - open traefik_conf/dynamic_conf.toml: no such file or directory"
`
Also

**Comment by jzanecook** [comment]
You should surround multi line quotes with ` ``` ` so that the formatting is correct (I am on mobile and my brain hurts reading that)

**Comment by h0lybyte** [comment]
The environmental variables are in the config of `evo_ve2` . Now I believe we would use a command / entrypoint to add them in.

**Comment by jzanecook** [comment]
All we need then is the entry point command for Traefik since that's what was stopping me last night. I don't know what the actual command for Traefik is or whether the commands variable is compatible with the entrypoint variable in the docker compose.

If the environment variables are in a file and we've specified that with config, all we would need is to add `source ~/evo_ve2` as one of the lines in the entrypoints, that or `. ~/evo_ve2`, I'm not sure what the difference is exactly.

**Comment by h0lybyte** [comment]
```
= 'echo "Domain is "' is not a Traefik command: assuming shell execution.
/entrypoint.sh: exec: line 18: echo "Domain is ": not found
= 'echo "Domain is "' is not a Traefik command: assuming shell execution.
/entrypoint.sh: exec: line 18: echo "Domain is ": not found
= 'echo "Domain is "' is not a Traefik command: assuming shell execution.
/entrypoint.sh: exec: line 18: echo "Domain is ": not found

```

When I did -> 

`    command:
      - echo "Domain is ${DOMAIN}" 
`

It seems that the `-command` is using entry point.

**Comment by jzanecook** [comment]
Okay so that tells me two things
- It did evaluate the variable and the variable was empty
- It did not just echo into the abyss and instead errored

What if you run 'export DOMAIN=ve2.kbve.com'?

**Comment by h0lybyte** [comment]
The solution right now that I see, Navigator Ziggy, is that the first line of the `-command` would be to set the `evo_ve2` as the environment.

**Comment by h0lybyte** [comment]
leaking the email, summer gotcha.

**Comment by jzanecook** [comment]
Got it to work by doing the following:

- Forgo the environment **file** and just put the damn values into the docker-compose.yml I mean like honestly who tf is gonna be looking at our docker-compose.yml and discovering secret information, the most they can get from it is the hash that htpasswd generated and the address it's gonna be pointing to and the email being used for acme-staging-v02 for letsencrypt.
- That was it.

**Comment by h0lybyte** [comment]
> Got it to work by doing the following:

I wonder which morty we are talking about. He did not mention the die hard binary that he should have used.

**Comment by h0lybyte** [comment]
After spending 10~ hours, I realized that I was in a simulation. I actually only ended up spending like 30 seconds.

**Comment by h0lybyte** [comment]
https://docs.docker.com/compose/compose-file/compose-versioning/#version-35
3.5 ->
```
Introduces the following additional parameters:

[isolation](https://docs.docker.com/compose/compose-file/compose-file-v3/#isolation) in service definitions
name for networks, secrets and configs
shm_size in [build configurations](https://docs.docker.com/compose/compose-file/compose-file-v3/#build)
```
3.8 ->
https://docs.docker.com/compose/compose-file/compose-versioning/#version-38
```
Introduces the following additional parameters:

[max_replicas_per_node](https://docs.docker.com/compose/compose-file/compose-file-v3/#max_replicas_per_node) in placement configurations
template_driver option for [config](https://docs.docker.com/compose/compose-file/compose-file-v3/#configs-configuration-reference) and [secret](https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets-configuration-reference) configurations. This option is only supported when deploying swarm services using docker stack deploy.
driver and driver_opts option for [secret](https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets-configuration-reference) configurations. This option is only supported when deploying swarm services using docker stack deploy.

```

**Comment by jzanecook** [comment]
Marked as Blocked, need to get the rest of the infrastructure working before we move forward with setting up Kubernetes in any variety.

**Comment by h0lybyte** [comment]
Okay k3s is up and running on the k8s clusters. They are all under portainer and are healthy / functional.
