### ISSUE TITLE
Portainer 2.15.1 Release

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#38]
**Describe the update**
A clear and concise description of what the update will be. Keep it simple!

* * *

**References for update**
[1] https://github.com/portainer/portainer/releases
```
Overview of changes
New Portainer CE 2.15.1 release

Docker:
Fixed an issue with connecting to the local Docker environment when using Windows Container Services. https://github.com/portainer/portainer/issues/7618
Fixed an issue where the build image button would stay inactive when using a tar file. https://github.com/portainer/portainer/issues/7624
Added re-pull image option to Docker stacks. https://github.com/portainer/portainer/issues/7671
Portainer:
Fixed an issue where some colors in dark mode appeared too brown. https://github.com/portainer/portainer/issues/7616
Fixed an issue when using leading or trailing spaces in a password would break the login process. https://github.com/portainer/portainer/issues/7621
```

* * *

**Security risk**
Are there any major security risks. No.

* * *

**Comment by h0lybyte** [comment]
![Sus](https://i.imgur.com/OhkJ8by.png)
ඞ
2.9? Damn they are sus.

We should do 2.15.1 or we could do latest? I took a backup, going to run the latest.

**Comment by h0lybyte** [comment]
@jzanecook  -> 3 tasks below. I already backed up the portainer configs and the qEMU 100. 

[1] Pull the portainer-agent-stack.yml and add it into the kbve.com site (under /data/portainer/, create a folder called stack and call it `docker-compose_portainer_portainer-agent_traefik.yml`) ? Maybe we need a better naming convention but at the same time something that gets the general information across the board. 

[2] Maybe we tag remove the specific version tag (2.15.1 / 2.15.0) and have it just pull the latest? I am not too sure if we need the `latest` tag. 

[3] We can then just run a docker stack restart , it should then just automatically pull the latest, thus updating it.

**Comment by h0lybyte** [comment]
[2] https://docs.portainer.io/start/upgrade/swarm
```
Always match the agent version to the Portainer Server version. In other words, when you're installing or upgrading to Portainer 2.15.1 make sure all of the agents are also on version 2.15.1.
```

I see they have latest tag. 
![latest](https://i.imgur.com/04y5Fhi.png)

**Comment by jzanecook** [comment]
Alright I ran the two commands you listed, I also edited the portainer config to include "latest" just in case we need to start it back up in the future rather than 2.15.0.

**Comment by h0lybyte** [comment]
The portainer agent in the VE2 swarm is still 2.15? 
We should re open this until we can confirm that watchtower updates them.

**Comment by h0lybyte** [comment]
Looks like the containers are still on 2.15.0 ~ 

Do you think we mis configured watchtower? Should we just manually update them?

On the side note, I noticed on 1059 that the DNS was not working. I was able to resolve that, I think. So that might help with those constant failures upon deployment to that box.

**Comment by h0lybyte** [comment]
Okay k8s and docker swarm are at 2.15.1.
Going to close this.
