### ISSUE TITLE
Ads and floating UI overlapping with text 

### ISSUE THREAD

**Issue by RangerDevv** [KBVE/kbve.com#382]
**Describe the bug**
There is a problem where the ads and the floating UI conflict with text and make it 

* * *

**To Reproduce**

1. Go to 'news'
2. Scroll down to
3. The text overlapping with the ads.

* * *

**Expected behavior**
The text should not be obstructed by other UI elements such as ads and floating buttons 

* * *

**Screenshots**
![Screenshot_20230314-105326.png](https://user-images.githubusercontent.com/66392962/225045115-2fd0a9fe-a70d-4cb4-b790-0315526981cf.png)

* * *

**Desktop (please complete the following information):**

**Mobile (please complete the following information):**

- Device: mobile with small screen (iphone SE, Motorola one 5G ace)

* * *

**Additional context**
I would recommend moving the floating buttons to the top right or make it included in the navbar. 

* * *

**Comment by h0lybyte** [comment]
Automating Tasker
* * *
[KBVE Support](https://kbve.com/support/)
* * *
[HubSpot Ticket Created](https://app.hubspot.com/contacts/20854121/ticket/1496669969)
* * *

**Comment by h0lybyte** [comment]
Honestly I am close to just dropping them as an advertisement, however I will see what I can do in the mean time. Maybe I might just not have the side menu floaters , because I have not yet built them out. Hmm if anyone has suggestions, please feel free to chime in?

**Comment by h0lybyte** [comment]
Yeah i was thinking it might be better to just merge them into the menu bar and have the click -> action display the modal.

**Comment by h0lybyte** [comment]
> One suggestion is to not put ads on the bottom of the screen. Like stick to the bottom of screen if yk what I mean. Another option is to increase the bottom padding so that the user can scroll a bit further down to read. Lastly, you can move the floating buttons to the navbar or just scrap them entirely.

Yeah I just disabled the anchor ad, it seems to be more annoying than anything else.
