### ISSUE TITLE
Concept:  n8n on VM100

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#39]
**Core Concept/Theory**
We should start looking into adding n8n as a docker container within our instance of VM100.

* * *

**Alternative Ideas**
As we start to get the main api running, we can look into the automation of various services.

* * *

**Alternative Examples/Sources**
I ran a local instance of n8n, I suggest doing the same.

* * *

**Additional information**
[1] Install Guide -> https://docs.n8n.io/hosting/installation/docker/

**Comment by jzanecook** [comment]
Marking as Blocked, need SSL on strapi first.

**Comment by h0lybyte** [comment]
Updating to `Pending` . 

Started the docker compose basics, we will have to get authelia up and running this weekend, so that no random entity can just connect to our n8n instance. 

So today, I will start the n8n page @ https;//kbve.com/application/n8n and the docker compose will be in https://kbve.com/data/n8n

**Comment by h0lybyte** [comment]
n8n has some issues accessing information and websockets because of our harden security. The solution will be creating a reverse proxy that allows access for certain ip blocks / paths. 

I looked over it all and I can say that we can safely operate n8n, but not at 100%, its still at around 90% until we build a gateway, but that gateway will be outside of n8n, thus closing this out.
