### ISSUE TITLE
Music Theory: "Going to work"

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#43]
**Describe the music topic**
Music Theory: "Going to work"

00:00 : 00:30 - Intro Lofi Punk
00:29 - 01:00 - Verse1 from @PeacefulFire
01:00 - 01:25 - Longer Chorus Phuck Work
01:15 - 01:30 - Verse2 from @PeacefulFire 

~Phuck Work~

* * *

**Reference Material**
A collection of links, papers, and/or data related to the topic. (Please use the number inside bracket for each ref.)
[1]...
[2]...
[3]...

* * *

~~

**Comment by h0lybyte** [comment]
[1] https://www.youtube.com/watch?v=Wqb39YhgTgs

Part of the intro ^

**Comment by PeacefulFire** [comment]
Acknowledged.

**Comment by PeacefulFire** [comment]
I'm here for the company
Not here for the capital
Been agitate lately
Actually Anti-affable, maybe

**Comment by h0lybyte** [comment]
Going to close this out and will open a new ticket it when we talk over it again.

**Comment by h0lybyte** [comment]
Automating Tasker
* * *
[KBVE Support](https://kbve.com/support/)
* * *
[KBVE Discord](https://kbve.com/discord/)
* * *
[KBVE Staff](https://kbve.com/team/)
* * *
[KBVE VIP Priority](https://kbve.com/vip/) || [KBVE Community](https://kbve.com/c/)
* * *
[HubSpot Ticket Created](https://app.hubspot.com/contacts/20854121/ticket/1546857534)
* * *
