### ISSUE TITLE
[Search] : Feedback from Ziggy

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#481]
**Describe the bug**
Just general feedback from Ziggy:

"
add a transition to the background change (e.g. `transition: all 195ms ease;`) and give it a lighter background color when hovered (really only needs to go from transparent to slightly lighter but still transparent, e.g. `hovered: { background-color: rgba(255, 255, 255, 0.12); }`), make the font the same as the rest of the website's font if possible, add a rounded border to the search textfield, move the search button into the text field (you can do this by making the textfield itself transparent but surround it, the X button, and the search button with a div that's flex-direction: row, align-items: center, and then give the text field flex: 1). The dropdown for relevance/date needs to fit the minimum of the text (I see "Relevan" with ce clipping off the edge) and the Sort By needs to be aligned, you should take the container that the results and the sort dropdown are in and turn them into a flex-box and ensure that the section for the sort has align-content: center and the dropdown has whitespace: nowrap
Page buttons and that whole section at the bottom should fit the theme of the items above
"

Going to go through it all and break it down further into mini-goals.
* * *

**Comment by h0lybyte** [comment]
Automating Tasker
* * *
[KBVE Support](https://kbve.com/support/)
* * *
[KBVE Discord](https://kbve.com/discord/)
* * *
[KBVE Staff](https://kbve.com/team/)
* * *
[KBVE VIP Priority](https://kbve.com/vip/) || [KBVE Community](https://kbve.com/c/)
* * *
[HubSpot Ticket Created](https://app.hubspot.com/contacts/20854121/ticket/1597654436)
* * *

**Comment by h0lybyte** [comment]
Automating Tasker
* * *
[KBVE Support](https://kbve.com/support/)
* * *
[KBVE Discord](https://kbve.com/discord/)
* * *
[KBVE Staff](https://kbve.com/team/)
* * *
[KBVE VIP Priority](https://kbve.com/vip/) || [KBVE Community](https://kbve.com/c/)
* * *
[HubSpot Ticket Created](https://app.hubspot.com/contacts/20854121/ticket/1597660762)
* * *

**Comment by PeacefulFire** [comment]
Reviewed KBVE Search - is serviceable, but the syntax of ?q=lorem+ipsum+dolor  stays in the URL for subsequent searches in the box. And its still working. Perhaps it should cut off so all searched topics appear consistent in the URL bar

**Comment by h0lybyte** [comment]
Okay we could do that. 

I suppose we move the search logic into the react component to do so?

**Comment by h0lybyte** [comment]
I believe we could migrate the search form into a react-form but for now it looks like that the basics are working fine.

I will close this ticket out when the branch moves into production.

**Comment by h0lybyte** [comment]
Merged the updated template into the main branch. Going to close this out and please create a new issue / ticket for future problems with the Search.
