### ISSUE TITLE
[RJ] : [Error: andsam fails to load roguejester

### ISSUE THREAD

**Issue by slamjamuels** [KBVE/kbve.com#643]
**Describe the Update/Upgrade/Issue**
andsam fails to load roguejester via local repository (cloned from github)

* * *

**References for Update**
![image](https://github.com/KBVE/kbve.com/assets/7191977/0a11479c-0d44-4aab-a9c9-cbb91c79855f)
![image](https://github.com/KBVE/kbve.com/assets/7191977/5e6aa073-b3e2-409e-b17a-8f32a9e7e315)

* * *

**Security/Performance Risk**
N/A

* * *

**Comment by h0lybyte** [comment]
Automating Tasker
* * *
[KBVE Support](https://kbve.com/support/)
* * *
[KBVE Discord](https://kbve.com/discord/)
* * *
[KBVE Staff](https://kbve.com/team/)
* * *
[KBVE VIP Priority](https://kbve.com/vip/) || [KBVE Community](https://kbve.com/c/)
* * *
[HubSpot Ticket Created](https://app.hubspot.com/contacts/20854121/ticket/1722792550)
* * *

**Comment by h0lybyte** [comment]
Automating Tasker
* * *
[KBVE Support](https://kbve.com/support/)
* * *
[KBVE Discord](https://kbve.com/discord/)
* * *
[KBVE Staff](https://kbve.com/team/)
* * *
[KBVE VIP Priority](https://kbve.com/vip/) || [KBVE Community](https://kbve.com/c/)
* * *
[HubSpot Ticket Created](https://app.hubspot.com/contacts/20854121/ticket/1722794413)
* * *

**Comment by h0lybyte** [comment]
Automating Tasker
* * *
[KBVE Support](https://kbve.com/support/)
* * *
[KBVE Discord](https://kbve.com/discord/)
* * *
[KBVE Staff](https://kbve.com/team/)
* * *
[KBVE VIP Priority](https://kbve.com/vip/) || [KBVE Community](https://kbve.com/c/)
* * *
[HubSpot Ticket Created](https://app.hubspot.com/contacts/20854121/ticket/1722427460)
* * *

**Comment by h0lybyte** [comment]
Automating Tasker
* * *
[KBVE Support](https://kbve.com/support/)
* * *
[KBVE Discord](https://kbve.com/discord/)
* * *
[KBVE Staff](https://kbve.com/team/)
* * *
[KBVE VIP Priority](https://kbve.com/vip/) || [KBVE Community](https://kbve.com/c/)
* * *
[HubSpot Ticket Created](https://app.hubspot.com/contacts/20854121/ticket/1722752952)
* * *

**Comment by h0lybyte** [comment]
Automating Tasker
* * *
[KBVE Support](https://kbve.com/support/)
* * *
[KBVE Discord](https://kbve.com/discord/)
* * *
[KBVE Staff](https://kbve.com/team/)
* * *
[KBVE VIP Priority](https://kbve.com/vip/) || [KBVE Community](https://kbve.com/c/)
* * *
[HubSpot Ticket Created](https://app.hubspot.com/contacts/20854121/ticket/1722762806)
* * *

**Comment by h0lybyte** [comment]
Could it be your firewall software that is blocking the 3rd party URLs?

I remember that you had issues with Git and your firewall software in the past. 

Furthermore, do you have git installed as a global path within Windows?

**Comment by h0lybyte** [comment]
@slamjamuels is currentlying looking at this solution from StackOverFlow.

https://stackoverflow.com/questions/72389135/unity-cant-add-git-packages-on-external-ssd-fatal-not-in-a-git-directory

I do recall running into long path issues with Windows 10, as they limit the size of the folder name.

I am not thinking it is a firewall issue but rather just a git issue and the permissions related to that. But we shall find out later after he goes through this solution.

**Comment by h0lybyte** [comment]
https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows

**Comment by slamjamuels** [comment]
![bootingUnity_july2023](https://github.com/KBVE/kbve.com/assets/7191977/b82002b3-b77f-4b9a-b0fa-e786a8a7e64f)

**Comment by h0lybyte** [comment]
This was resolved for the most part. 
Going to close this out.
