### ISSUE TITLE
[Update] : [Project] : Charles - Schedule overview meeting.

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#679]
**Describe the update**

We should do a meeting over [Charles - the super computer](https://kbve.com/project/charles). I am thinking we could do a mini-charles first to identify issues like not having enough power, proper ventilation, ect.. 

Some of the key components to building this homelab machine learning computer would be identifying the resources that would be required to be purchased. How much ram does it need? What sticks are okay? Does it need multiple GPUs? ect...

This ticket is just design to set a friendly time / meeting regarding it. 

* * *

**References for update**
Include any links / data for the update that must be done.
[Official Document for Charles](https://kbve.com/project/charles)

* * *

**Security/Performance risks**
Are there any major security and/or performance risks?!
This is a tough set of questions because we have look over both the performance and security metrics. 
We do not want something too weak that it cant train a model but we also do not want something that can cause a massive fire... think silicon valley scene of server fire xD

* * *

**Comment by h0lybyte** [comment]
Automating Tasker
* * *
[KBVE Support](https://kbve.com/support/)
* * *
[KBVE Discord](https://kbve.com/discord/)
* * *
[KBVE Staff](https://kbve.com/team/)
* * *
[KBVE VIP Priority](https://kbve.com/vip/) || [KBVE Community](https://kbve.com/c/)
* * *
[HubSpot Ticket Created](https://app.hubspot.com/contacts/20854121/ticket/1745907115)
* * *

**Comment by h0lybyte** [comment]
We will be grabbing the parts to build Charles today,

- 2 x 4090s 
- 128gb of ram
- intel i9
- SSDs
ect....

I will keep this ticket open for the assembly and structure of Charles

**Comment by h0lybyte** [comment]
We could go the route of github self-hosted containers and then call them via github actions. 
This would save us time in building out and test casing, which is where I am thinking the best move would be. 
Getting the iso down, formatted and self-updating is the key, so that we have basically an unattended iot-style server? 

Thoughts?

**Comment by h0lybyte** [comment]
Reference to custom self hosted runner -> https://stackoverflow.com/questions/71579731/github-actions-run-multiple-jobs-in-a-single-runner-or-share-workspace-between

**Comment by qstephen18** [comment]
> We could go the route of github self-hosted containers and then call them via github actions. This would save us time in building out and test casing, which is where I am thinking the best move would be. Getting the iso down, formatted and self-updating is the key, so that we have basically an unattended iot-style server?
> 
> Thoughts?

Sounds interesting. Will look through reference.

**Comment by h0lybyte** [comment]
> > We could go the route of github self-hosted containers and then call them via github actions. This would save us time in building out and test casing, which is where I am thinking the best move would be. Getting the iso down, formatted and self-updating is the key, so that we have basically an unattended iot-style server?
> > Thoughts?
> 
> Sounds interesting. Will look through reference.

Getting the software to work, scale and cluster is actually getting easier as there are a ton of new libraries and tech coming out each year. So the github self-hosted runner route would make it so that there is a bit less stress on our docker swarm setup.

**Comment by qstephen18** [comment]
> > > We could go the route of github self-hosted containers and then call them via github actions. This would save us time in building out and test casing, which is where I am thinking the best move would be. Getting the iso down, formatted and self-updating is the key, so that we have basically an unattended iot-style server?
> > > Thoughts?
> > 
> > 
> > Sounds interesting. Will look through reference.
> 
> Getting the software to work, scale and cluster is actually getting easier as there are a ton of new libraries and tech coming out each year. So the github self-hosted runner route would make it so that there is a bit less stress on our docker swarm setup.

That makes sense, have the runner help out/share load. I think that's a good plan.

**Comment by h0lybyte** [comment]
The only drawback is that we would be more dependent on the GitHub system but I think it's worth it because it would save us time in the long term. For example, if I want a new blog post for KBVE, I would just write out an issue ticket like this:

`[Atlas] Make me a new blogpost`

Then in the description, we would include what we would want in the blog post and then have it make a pull request against the repo with the new blog post. The majority of the blog posts would be generated using an LLM, at least that is where I am at with this current concept.

**Comment by qstephen18** [comment]
> The only drawback is that we would be more dependent on the GitHub system but I think it's worth it because it would save us time in the long term. For example, if I want a new blog post for KBVE, I would just write out an issue ticket like this:
> 
> `[Atlas] Make me a new blogpost`
> 
> Then in the description, we would include what we would want in the blog post and then have it make a pull request against the repo with the new blog post. The majority of the blog posts would be generated using an LLM, at least that is where I am at with this current concept.

True, we save time/reduce some technical debt by allowing the GitHub system to share some of the load.

**Comment by h0lybyte** [comment]
Going to close this out, as I am migrating it over to https://github.com/KBVE/kbve/issues/96
