### ISSUE TITLE
[Concept] : Meme.sh - Hackathon F.inc

### ISSUE THREAD

**Issue by h0lybyte** [KBVE/kbve.com#777]
**Core Concept/Theory**
A clear and concise description of what the concept is. Ex. It would be cool if [...]

For the next hackathon, I am going to refine some of the libraries and try to streamline everything, so that it is easier and easier to build and expand from.

[Main Hackathon Event](https://arenax.f.inc/)

I am thinking we produce a `blog post` ?!

- ATHLETIC PERFORMANCE/RECOVERY
- SPORTS ANALYTICS
- GAMING
- MEDIA PRODUCTION AND BROADCASTING
- FAN ENGAGEMENT

So we are targeting the area of Media Production and Fan Engagement? 

This is all subject to change and pivots are welcome, please let me know where we want to go with this.

* * *

**Alternative Ideas**
Is there any other way this concept could be used?

No major alternative ideas as of right now.

* * *

**Alternative Examples/Sources**
Are there any other references that you can provide?

- [NBA CBA Ai Chat](https://github.com/mckaywrigley/nba-cba-ai-chat/tree/main)

* * *

**Additional information**
Add any other context or examples of this concept here.

I will update this with additional information as I get more data.

**Comment by h0lybyte** [comment]
- [Canvas Fermat](https://canvas.fermat.app/permalink?perma=64e55e4360026286f0f989d6)
- Notion URL?

**Comment by 8gratitude8** [comment]
Notion Doc : https://www.notion.so/abe263e547dc482abd2799870271f095?v=42fb1c352c074733ae89c1ce85397630

**Comment by h0lybyte** [comment]
If we want to test case Clarifai, we could do it in this hackathon as an example. 

Then we would be preparing ourselves for the major one this weekend? 

I will continue working on the front end and general integration. For this NBA project, I think we should keep it very simple and go with a one page style application.

**Comment by h0lybyte** [comment]
Looks like I misunderstood what we needed for this, so I will close this out for now.
