### ISSUE TITLE
Harden the USS KBVE Mk.1

### ISSUE THREAD

**Issue by jzanecook** [KBVE/kbve.com#9]

**Comment by h0lybyte** [comment]
We still have to harden the dedicated server?
[1] https://www.cyberciti.biz/tips/linux-security.html

We could extend the documentation on the linux security with all our information. I wounder if there is a AIO script that helps with the harden process.

**Comment by h0lybyte** [comment]
[2] https://www.pluralsight.com/blog/it-ops/linux-hardening-secure-server-checklist

I am not too use about the USB hardening but we could go through the PAM stuff.

**Comment by h0lybyte** [comment]
This has been done. 

We using [Ansible/AWX](https://kbve.com/application/ansible/) and will expand it into Github Actions.
